# 指定CircleCI配置文件的版本
version: 2

# 定义deploy-vue job的详细步骤
jobs:
  deploy:
    # 使用指定的Docker镜像
    docker:
      - image: circleci/node:16
    # 步骤列表
    steps:
      # 检出代码
      - checkout
      # 从缓存中恢复依赖，提高构建速度
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      # 安装项目依赖
      - run:
          name: Install dependencies
          command: |
            npm install
      # 保存依赖到缓存，供下次构建使用
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # 构建并部署Vue应用
      - run:
          name: Build and Deploy
          command: |
            npm build
            npm gh-pages:deploy
